### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by jwaterloo** [sumeetchhetri/ffead-cpp#5]
I am "desperately need help on windows". Once I can get it working, ffead-cpp may be the best free non commercial open source web framework for C++.

Some of many things I like reading about thus far:
1) Coming from the Java world the Spring like XML, reflection based, IOC, inversion of control. Configuration based on structured objects is way better than flattened name value pairs.
2) Coming from the Java world, log4j styled logging
3) C++ Interpreter for when certain business rules needs to be runtime configurable, either from database of configuration file.
4) runtime reflection is also nice though more documentation is needed on building the metadata

WARNING: Be careful imitating too much from other language libraries and frameworks. Many times the design is bad and has already been replaced by something better.

For instance, Template file and Dynamic C++ Page imitates the strength of ASP not ASP.NET, JSP not JSF and PHP not Yii. However, it also inherits the weakess of working on something that is neither C++ or HTML.

What's still needed
1) Auto compile, load, swap C++ code: The beauty of "Dynamic C++ Page" is you change, save and refresh page. Short test cycles improves developers productivity. Problem is if the language is not your native language than it sucks. Since Controller follows a well defined interface we need to be able to save it. It automatically recompiles as a dll/so and dynamically gets swapped out. This one interface is nice but possibly with future stateless interfaces; dependency injected of course. Now that C+ has raw strings so that w can have HTML or XML inside of our C++ code, this would be awesome.
2) Graphic Designers are better at creating HTML pages than programmers. As such it is better if the textual portion of the view in a MVC framework was actually pure html. I know it never made a splash in the Java world, poor advertising, but Java RSF still can't be touched
3) Flash scope memory, short lived session, for transferring data immediately between requests
4) At some point data binding, conversion is needed to convert, request data into programmer data. in PHP and JQuery a request parameter named, "abc.def[3].ght" with a value of 5 would automatically be turned into 2 objects, one array and 1 member initialization. Maybe with your reflection and some configuration there could be something that flatten an typed object tree into map of string of strings or deflatten the opposite. A cross between compile time and runtime reflection could even make this typesafe for speed and refactoring.

A frameworks worst enemy is growing into a monlith so of course all of these are better served as separate libraries that could be used in any scenario.

**Comment by daminetreg** [comment]
Did you try cppcms? it build fines on every platform and is maintained by a boost library maintainer.                                                                                                                                                                                                                                                                                                                                        --Damien Buhl                                                                                                                                                                                                                From: jwaterlooSent: vendredi 6 février 2015 21:35To: sumeetchhetri/ffead-cppReply To: sumeetchhetri/ffead-cppSubject: [ffead-cpp] Wishlist (#5)I am "desperately need help on windows". Once I can get it working, ffead-cpp may be the best free non commercial open source web framework for C++.

Some of many things I like reading about thus far:
1) Coming from the Java world the Spring like XML, reflection based, IOC, inversion of control. Configuration based on structured objects is way better than flattened name value pairs.
2) Coming from the Java world, log4j styled logging
3) C++ Interpreter for when certain business rules needs to be runtime configurable, either from database of configuration file.
4) runtime reflection is also nice though more documentation is needed on building the metadata

WARNING: Be careful imitating too much from other language libraries and frameworks. Many times the design is bad and has already been replaced by something better.

For instance, Template file and Dynamic C++ Page imitates the strength of ASP not ASP.NET, JSP not JSF and PHP not Yii. However, it also inherits the weakess of working on something that is neither C++ or HTML.

What's still needed
1) Auto compile, load, swap C++ code: The beauty of "Dynamic C++ Page" is you change, save and refresh page. Short test cycles improves developers productivity. Problem is if the language is not your native language than it sucks. Since Controller follows a well defined interface we need to be able to save it. It automatically recompiles as a dll/so and dynamically gets swapped out. This one interface is nice but possibly with future stateless interfaces; dependency injected of course. Now that C+ has raw strings so that w can have HTML or XML inside of our C++ code, this would be awesome.
2) Graphic Designers are better at creating HTML pages than programmers. As such it is better if the textual portion of the view in a MVC framework was actually pure html. I know it never made a splash in the Java world, poor advertising, but Java RSF still can't be touched
3) Flash scope memory, short lived session, for transferring data immediately between requests
4) At some point data binding, conversion is needed to convert, request data into programmer data. in PHP and JQuery a request parameter named, "abc.def[3].ght" with a value of 5 would automatically be turned into 2 objects, one array and 1 member initialization. Maybe with your reflection and some configuration there could be something that flatten an typed object tree into map of string of strings or deflatten the opposite. A cross between compile time and runtime reflection could even make this typesafe for speed and refactoring.

A frameworks worst enemy is growing into a monlith so of course all of these are better served as separate libraries that could be used in any scenario.

—Reply to this email directly or view it on GitHub.
